# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomid', models.CharField(blank=True, max_length=200)),
                ('start_datetime', models.CharField(blank=True, max_length=200)),
                ('end_datetime', models.CharField(blank=True, max_length=200)),
                ('date', models.CharField(blank=True, max_length=200)),
                ('siteid', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('contact', models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
