# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-25 22:51
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20170225_2143'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, max_length=500, unique=True),
        ),
    ]
