# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_query_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='last_accessed',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
