# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_query_last_accessed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='uuid',
        ),
        migrations.AddField(
            model_name='query',
            name='hash',
            field=models.CharField(default='not-a-good-hash', max_length=500, unique=True),
            preserve_default=False,
        ),
    ]
