# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 19:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20170227_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
